package com.kodilla.exception.test.zadanie2;

public class SecondChallenge {
}
